version: "3"

services:
  appweb:
    container_name: vocabularyapp
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongodb

  mongodb:
    container_name: mongoDataBase
    image: mongo
    ports:
      - "27019:27017"